language: android

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools
    # Tools repetead on purpose as instructed in https://docs.travis-ci.com/user/languages/android/

    # The BuildTools version used by your project
    - build-tools-25.0.0

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-16

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86_64-android-19
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17
    # TODO: Configure travis to run in more than one emulator

jdk:
    - oraclejdk8

before_install:
  - . .travis/install-ndk
  - $ANDROID_NDK/ndk-build --version
  - . .travis/install-buck
  - PATH=`pwd`/buck/bin:$PATH
  - export PATH
  # Building .AAR, needed for instrumentation tests (they depend on the prebuilt_aar)
  - ./gradlew build --no-daemon
  # Emulator Management: Create, Start and Wait
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - instrumentTest/crypto/run
  # Check benchmarks build (even if not run) (later, when I fix the code)
  #- buck build benchmarks
  #- buck build benchmarks/app
